name: Add new tools

on:
  repository_dispatch:
    types: add-new-tools
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.GHA_DEPLOY_KEY }}
        fetch-depth: '2'
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f jenkins/requirements.yml ]; then pip install -r jenkins/requirements.yml; fi
    - name: Install tools
      shell: bash
      env:
        PRODUCTION_API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
        STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
      run: |
        git config --local user.email "github-actions@usegalaxy.no"
        git config --local user.name "usegalaxy.no actions"
        bash -x jenkins/main.sh install
